// <auto-generated />
using System;
using AthenaXI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AthenaXI.Data.Migrations
{
    [DbContext(typeof(AthenaXIDbContext))]
    partial class AthenaXIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AthenaXI.Core.Models.AuctionBid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountCr")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("AuctionPlayerSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuctionSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BiddingUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRtm")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuctionSessionId");

                    b.HasIndex("BiddingUserId");

                    b.ToTable("AuctionBids");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.AuctionPlayerSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuctionOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuctionSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuctionSet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BasePriceCr")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("BidIncrementCr")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RtmTeam")
                        .HasColumnType("text");

                    b.Property<string>("SetDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("AuctionSessionId", "AuctionOrder")
                        .IsUnique();

                    b.ToTable("AuctionPlayerSlots");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.AuctionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuctionSessionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("FinalPriceCr")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasRtm")
                        .HasColumnType("boolean");

                    b.Property<bool>("WentUnsold")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("WinningUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("AuctionSessionId", "PlayerId")
                        .IsUnique();

                    b.ToTable("AuctionResults");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.AuctionSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("AuctionSessions");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.MatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTransferWindowOpen")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Team1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Team2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "MatchNumber")
                        .IsUnique();

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePriceCr")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("BattingStyle")
                        .HasColumnType("text");

                    b.Property<string>("BowlingStyle")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IPLTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOverseas")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUncapped")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.PlayerMatchPoints", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BallsFaced")
                        .HasColumnType("integer");

                    b.Property<decimal>("BasePoints")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("Catches")
                        .HasColumnType("integer");

                    b.Property<bool>("DidPlay")
                        .HasColumnType("boolean");

                    b.Property<int>("DotBalls")
                        .HasColumnType("integer");

                    b.Property<string>("EditReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Fours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBowled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDuck")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLbw")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManuallyEdited")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRunOutAssist")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRunOutDirect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStumping")
                        .HasColumnType("boolean");

                    b.Property<int>("MaidenOvers")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchEventId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OversBowled")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Runs")
                        .HasColumnType("integer");

                    b.Property<int>("RunsConceded")
                        .HasColumnType("integer");

                    b.Property<int>("Sixes")
                        .HasColumnType("integer");

                    b.Property<bool>("WasDismissed")
                        .HasColumnType("boolean");

                    b.Property<int>("Wickets")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchEventId");

                    b.HasIndex("PlayerId", "MatchEventId")
                        .IsUnique();

                    b.ToTable("PlayerMatchPoints");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AuctionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SeasonEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SeasonStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.SeasonConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BidTimerSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal>("BudgetPerTeamCr")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("CaptainMultiplier")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal>("DefaultBidIncrementCr")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("ImpactPlayerMultiplier")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("MaxOverseasPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSquadSize")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSwapsPerWindow")
                        .HasColumnType("integer");

                    b.Property<int>("MinSquadSize")
                        .HasColumnType("integer");

                    b.Property<int>("MinUncappedPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinWicketKeepers")
                        .HasColumnType("integer");

                    b.Property<int>("PlayingXIBonusPoints")
                        .HasColumnType("integer");

                    b.Property<decimal>("PlayingXIMultiplier")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("Pt100RunBonus")
                        .HasColumnType("integer");

                    b.Property<int>("Pt25RunBonus")
                        .HasColumnType("integer");

                    b.Property<int>("Pt3CatchBonus")
                        .HasColumnType("integer");

                    b.Property<int>("Pt3WicketBonus")
                        .HasColumnType("integer");

                    b.Property<int>("Pt4WicketBonus")
                        .HasColumnType("integer");

                    b.Property<int>("Pt50RunBonus")
                        .HasColumnType("integer");

                    b.Property<int>("Pt5WicketBonus")
                        .HasColumnType("integer");

                    b.Property<int>("Pt75RunBonus")
                        .HasColumnType("integer");

                    b.Property<int>("PtCatch")
                        .HasColumnType("integer");

                    b.Property<int>("PtDotBall")
                        .HasColumnType("integer");

                    b.Property<int>("PtDuck")
                        .HasColumnType("integer");

                    b.Property<int>("PtEcon10To11")
                        .HasColumnType("integer");

                    b.Property<int>("PtEcon11To12")
                        .HasColumnType("integer");

                    b.Property<int>("PtEcon5To6")
                        .HasColumnType("integer");

                    b.Property<int>("PtEcon6To7")
                        .HasColumnType("integer");

                    b.Property<int>("PtEcon7To10")
                        .HasColumnType("integer");

                    b.Property<int>("PtEconAbove12")
                        .HasColumnType("integer");

                    b.Property<int>("PtEconBelow5")
                        .HasColumnType("integer");

                    b.Property<int>("PtFourBonus")
                        .HasColumnType("integer");

                    b.Property<int>("PtLbwBowledBonus")
                        .HasColumnType("integer");

                    b.Property<int>("PtMaidenOver")
                        .HasColumnType("integer");

                    b.Property<int>("PtRun")
                        .HasColumnType("integer");

                    b.Property<int>("PtRunOutAssist")
                        .HasColumnType("integer");

                    b.Property<int>("PtRunOutDirect")
                        .HasColumnType("integer");

                    b.Property<int>("PtSixBonus")
                        .HasColumnType("integer");

                    b.Property<int>("PtSr130To150")
                        .HasColumnType("integer");

                    b.Property<int>("PtSr150To170")
                        .HasColumnType("integer");

                    b.Property<int>("PtSr50To60")
                        .HasColumnType("integer");

                    b.Property<int>("PtSr60To70")
                        .HasColumnType("integer");

                    b.Property<int>("PtSr70To130")
                        .HasColumnType("integer");

                    b.Property<int>("PtSrAbove170")
                        .HasColumnType("integer");

                    b.Property<int>("PtSrBelow50")
                        .HasColumnType("integer");

                    b.Property<int>("PtStumping")
                        .HasColumnType("integer");

                    b.Property<int>("PtWicket")
                        .HasColumnType("integer");

                    b.Property<int>("ReservePlayers")
                        .HasColumnType("integer");

                    b.Property<int>("RtmSlotsPerTeam")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("TransferWindow1AfterMatch")
                        .HasColumnType("integer");

                    b.Property<int>("TransferWindow2AfterMatch")
                        .HasColumnType("integer");

                    b.Property<int>("TransferWindow3AfterMatch")
                        .HasColumnType("integer");

                    b.Property<decimal>("ViceCaptainMultiplier")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId")
                        .IsUnique();

                    b.ToTable("SeasonConfigs");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.SyncJobLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Errors")
                        .HasColumnType("text");

                    b.Property<Guid>("MatchEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayersProcessed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchEventId");

                    b.ToTable("SyncJobLogs");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.TransferLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromPlayerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdminApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReserveActivation")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MadeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid?>("ToPlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransferWindow")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserTeamId");

                    b.ToTable("TransferLogs");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.UserTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BudgetRemainingCr")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<int>("RtmSlotsRemaining")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "SeasonId")
                        .IsUnique();

                    b.ToTable("UserTeams");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.UserTeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsImpactPlayer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReserve")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsViceCaptain")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PurchasedPriceCr")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UserTeamId", "PlayerId")
                        .IsUnique();

                    b.ToTable("UserTeamPlayers");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.AuctionBid", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.AuctionSession", "AuctionSession")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AthenaXI.Core.Models.User", "BiddingUser")
                        .WithMany("Bids")
                        .HasForeignKey("BiddingUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuctionSession");

                    b.Navigation("BiddingUser");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.AuctionPlayerSlot", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.AuctionSession", "AuctionSession")
                        .WithMany("PlayerSlots")
                        .HasForeignKey("AuctionSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AthenaXI.Core.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuctionSession");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.AuctionResult", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.AuctionSession", "AuctionSession")
                        .WithMany("Results")
                        .HasForeignKey("AuctionSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AthenaXI.Core.Models.Player", "Player")
                        .WithMany("AuctionResults")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuctionSession");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.AuctionSession", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.Season", "Season")
                        .WithMany("AuctionSessions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.MatchEvent", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.Notification", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.PlayerMatchPoints", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.MatchEvent", "MatchEvent")
                        .WithMany("PlayerPoints")
                        .HasForeignKey("MatchEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AthenaXI.Core.Models.Player", "Player")
                        .WithMany("MatchPoints")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchEvent");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.SeasonConfig", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.Season", "Season")
                        .WithOne("Config")
                        .HasForeignKey("AthenaXI.Core.Models.SeasonConfig", "SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.SyncJobLog", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.MatchEvent", "MatchEvent")
                        .WithMany("SyncLogs")
                        .HasForeignKey("MatchEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchEvent");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.TransferLog", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.User", "User")
                        .WithMany("Transfers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AthenaXI.Core.Models.UserTeam", "UserTeam")
                        .WithMany("Transfers")
                        .HasForeignKey("UserTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserTeam");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.UserTeam", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.Season", "Season")
                        .WithMany("Teams")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AthenaXI.Core.Models.User", "User")
                        .WithOne("Team")
                        .HasForeignKey("AthenaXI.Core.Models.UserTeam", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.UserTeamPlayer", b =>
                {
                    b.HasOne("AthenaXI.Core.Models.Player", "Player")
                        .WithMany("TeamSlots")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AthenaXI.Core.Models.UserTeam", "UserTeam")
                        .WithMany("Players")
                        .HasForeignKey("UserTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("UserTeam");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.AuctionSession", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("PlayerSlots");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.MatchEvent", b =>
                {
                    b.Navigation("PlayerPoints");

                    b.Navigation("SyncLogs");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.Player", b =>
                {
                    b.Navigation("AuctionResults");

                    b.Navigation("MatchPoints");

                    b.Navigation("TeamSlots");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.Season", b =>
                {
                    b.Navigation("AuctionSessions");

                    b.Navigation("Config");

                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.User", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Notifications");

                    b.Navigation("Team");

                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("AthenaXI.Core.Models.UserTeam", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Transfers");
                });
#pragma warning restore 612, 618
        }
    }
}
